name: Deploy CV API to Google Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or your Strapi-compatible version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Strapi
        run: npm run build

      - name: Create app.yaml
        run: |
          cat > app.yaml << EOF
          runtime: ${{ secrets.GCLOUD_RUNTIME }}
          instance_class: ${{ secrets.GCLOUD_INSTANCE_CLASS }}

          env_variables:
            NODE_ENV: ${{ secrets.NODE_ENV }}
            DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
            DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_SSL_REJECT_UNAUTHORIZED: ${{ secrets.DATABASE_SSL_REJECT_UNAUTHORIZED }}
          EOF

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet